sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  
jobs:
  include:
    - stage: Build Docker Image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t todo-client ./client/
      - docker images
      
